dependencies:
- -rotobuf==5.29.3
- absl-py==2.1.0
- addict==2.4.0
- aiofiles==22.1.0
- aiohttp==3.9.5
- aiosignal==1.3.1
- aiosqlite==0.20.0
- albumentations==1.3.1
- alembic==1.13.1
- annotated-types==0.7.0
- anyio==4.4.0
- appdirs==1.4.4
- argon2-cffi-bindings==21.2.0
- argon2-cffi==23.1.0
- argparse-dataclass==2.0.0
- arrow==1.3.0
- asttokens==2.4.1
- astunparse==1.6.3
- async-lru==2.0.4
- attrs==23.2.0
- babel==2.15.0
- beautifulsoup4==4.12.3
- biopython==1.83
- bleach==6.1.0
- blinker==1.8.2
- blosc2==2.6.2
- certifi==2024.6.2
- certipy==0.1.3
- cffi==1.16.0
- charset-normalizer==3.3.2
- click==8.0.4
- comm==0.2.2
- conda-inject==1.3.2
- configargparse==1.7
- connection-pool==0.0.3
- contourpy==1.2.1
- cryptography==42.0.8
- cycler==0.12.1
- cython==3.0.10
- dash-core-components==2.0.0
- dash-html-components==2.0.0
- dash-table==5.0.0
- dash==2.17.0
- datasets==3.5.0
- datetime==5.5
- datrie==0.8.2
- debugpy==1.8.1
- decorator==5.1.1
- defusedxml==0.7.1
- dill==0.3.8
- docker-pycreds==0.4.0
- docstring-parser==0.16
- docutils==0.21.2
- dpath==2.1.6
- efficientnet-pytorch==0.7.1
- entrypoints==0.4
- executing==2.0.1
- fastjsonschema==2.19.1
- filelock==3.14.0
- fire==0.7.0
- flask==3.0.3
- flatbuffers==24.3.25
- fonttools==4.53.0
- fqdn==1.5.1
- frozenlist==1.4.1
- fsspec==2024.6.0
- ftfy==6.3.1
- gast==0.5.4
- gitdb==4.0.11
- gitpython==3.1.43
- google-pasta==0.2.0
- greenlet==3.0.3
- grpcio==1.64.1
- h11==0.14.0
- h5py==3.11.0
- httpcore==1.0.5
- httpx==0.27.0
- huggingface-hub==0.30.2
- humanfriendly==10.0
- idna==3.7
- imageio==2.34.1
- immutables==0.20
- importlib-metadata==7.1.0
- importlib-resources==6.5.2
- iniconfig==2.0.0
- ipykernel==6.29.4
- ipython-genutils==0.2.0
- ipython==8.25.0
- ipywidgets==8.1.3
- isodate==0.6.1
- isoduration==20.11.0
- itsdangerous==2.2.0
- jax==0.4.28
- jaxlib==0.4.28+cuda12.cudnn89
- jedi==0.19.1
- jinja2==3.1.4
- joblib==1.4.2
- json5==0.9.25
- jsonargparse==4.9.0
- jsonpointer==2.4
- jsonschema-specifications==2023.12.1
- jsonschema==4.22.0
- jupyter-client==7.4.9
- jupyter-core==5.7.2
- jupyter-events==0.10.0
- jupyter-lsp==2.2.5
- jupyter-server-fileid==0.9.2
- jupyter-server-proxy==4.1.2
- jupyter-server-terminals==0.5.3
- jupyter-server-ydoc==0.8.0
- jupyter-server==2.14.1
- jupyter-ydoc==0.2.5
- jupyterhub==5.0.0
- jupyterlab-pygments==0.3.0
- jupyterlab-server==2.27.2
- jupyterlab-slurm==3.0.1
- jupyterlab-widgets==3.0.11
- jupyterlab==4.2.1
- keras-preprocessing==1.1.2
- keras==3.3.3
- kiwisolver==1.4.5
- lazy-loader==0.4
- libclang==18.1.1
- lightning-bolts==0.7.0
- lightning-flash==0.8.1.post0
- lightning-utilities==0.11.2
- lightning==2.2.5
- llvmlite==0.42.0
- mako==1.3.5
- markdown-it-py==3.0.0
- markdown==3.6
- markupsafe==2.1.5
- matplotlib-inline==0.1.7
- matplotlib==3.9.0
- mdurl==0.1.2
- meson==1.4.1
- mistune==3.0.2
- ml-dtypes==0.3.2
- more-itertools==10.2.0
- mpmath==1.3.0
- msgpack==1.0.8
- multidict==6.0.5
- multiprocess==0.70.16
- munch==4.0.0
- namex==0.0.8
- nbclassic==1.1.0
- nbclient==0.10.0
- nbconvert==7.16.4
- nbformat==5.10.4
- nbgitpuller==1.2.1
- ndindex==1.8
- nest-asyncio==1.6.0
- networkx==3.3
- ninja==1.11.1.1
- nose==1.3.7
- notebook-shim==0.2.4
- notebook==6.5.7
- numba==0.59.1
- numexpr==2.10.0
- numpy==1.23.5
- nvidia-cublas-cu12==12.1.3.1
- nvidia-cuda-cupti-cu12==12.1.105
- nvidia-cuda-nvcc-cu12==12.3.107
- nvidia-cuda-nvrtc-cu12==12.1.105
- nvidia-cuda-runtime-cu12==12.1.105
- nvidia-cudnn-cu12==8.9.2.26
- nvidia-cufft-cu12==11.0.2.54
- nvidia-curand-cu12==10.3.2.106
- nvidia-cusolver-cu12==11.4.5.107
- nvidia-cusparse-cu12==12.1.0.106
- nvidia-nccl-cu12==2.20.5
- nvidia-nvjitlink-cu12==12.3.101
- nvidia-nvtx-cu12==12.1.105
- oauthlib==3.2.2
- open3d==0.18.0
- opencv-contrib-python==4.10.0.82
- opencv-python-headless==4.11.0.86
- opencv-python==4.10.0.82
- openseespy==3.5.1.12
- openseespylinux==3.5.1.12
- opt-einsum==3.3.0
- optree==0.11.0
- overrides==7.7.0
- packaging==24.0
- pamela==1.1.0
- pandas==2.2.2
- pandoc==2.3
- pandocfilters==1.5.1
- parso==0.8.4
- pexpect==4.9.0
- pillow==10.3.0
- pip==23.2.1
- plac==1.4.3
- platformdirs==4.2.2
- plotly==5.22.0
- pluggy==1.5.0
- plumbum==1.8.3
- ply==3.11
- pretrainedmodels==0.7.4
- prometheus-client==0.20.0
- prompt-toolkit==3.0.46
- protobuf==3.20.1
- psutil==5.9.8
- ptyprocess==0.7.0
- pulp==2.8.0
- pure-eval==0.2.2
- py-cpuinfo==9.0.0
- pyarrow==19.0.1
- pybboxes==0.1.5
- pybis==1.36.3
- pycparser==2.22
- pydantic-core==2.18.4
- pydantic==2.7.3
- pydeprecate==0.3.2
- pyg-lib==0.4.0+pt22cu121
- pygments==2.18.0
- pyopenssl==24.1.0
- pyparsing==3.1.2
- pyqt5-qt5==5.15.2
- pyqt5-sip==12.13.0
- pyqt5==5.15.10
- pyquaternion==0.9.9
- pysam==0.22.1
- pystiche==1.0.1
- pytest==8.2.2
- python-dateutil==2.9.0.post0
- python-json-logger==2.0.7
- pytorch-lightning==1.9.5
- pytz==2024.1
- pyyaml==6.0.1
- pyzmq==26.0.3
- qtpy==2.4.1
- qudida==0.0.4
- rdflib==7.0.0
- referencing==0.35.1
- regex==2024.11.6
- requests==2.32.3
- reretry==0.11.8
- retrying==1.3.4
- rfc3339-validator==0.1.4
- rfc3986-validator==0.1.1
- rich==13.7.1
- rpds-py==0.18.1
- safetensors==0.5.2
- sahi==0.10.8
- scikit-image==0.23.2
- scikit-learn==1.5.0
- scipy==1.13.1
- scons==4.7.0
- seaborn==0.13.2
- segmentation-models-pytorch==0.4.0
- send2trash==1.8.3
- sentry-sdk==2.5.0
- setproctitle==1.3.3
- setuptools==59.5.0
- shapely==2.0.4
- simpervisor==1.0.0
- six==1.16.0
- smart-open==7.0.4
- smmap==5.0.1
- snakemake-interface-common==1.17.2
- snakemake-interface-executor-plugins==9.1.1
- snakemake-interface-report-plugins==1.0.0
- snakemake-interface-storage-plugins==3.2.2
- snakemake==8.13.0
- sniffio==1.3.1
- soupsieve==2.5
- sqlalchemy==2.0.30
- stack-data==0.6.3
- stopit==1.1.2
- sympy==1.12.1
- tables==3.9.2
- tabulate==0.9.0
- tenacity==8.3.0
- tensorboard-data-server==0.7.2
- tensorboard==2.16.2
- tensorflow-io-gcs-filesystem==0.37.0
- tensorflow==2.16.1
- tensorrt-cu12-bindings==10.0.1
- tensorrt-cu12-libs==10.0.1
- tensorrt-cu12==10.0.1
- tensorrt==10.0.1
- termcolor==2.4.0
- terminado==0.18.1
- terminaltables==3.1.10
- texttable==1.7.0
- threadpoolctl==3.5.0
- throttler==1.2.2
- tifffile==2024.5.22
- timm==1.0.15
- tinycss2==1.3.0
- tokenizers==0.21.1
- toposort==1.10
- torch-cluster==1.6.3+pt22cu121
- torch-fidelity==0.3.0
- torch-geometric==2.5.3
- torch-scatter==2.1.2+pt22cu121
- torch-sparse==0.6.18+pt22cu121
- torch-spline-conv==1.2.2+pt22cu121
- torch==2.3.1
- torchaudio==2.3.1
- torchmetrics==0.10.3
- torchvision==0.18.1
- tornado==6.4.1
- tqdm==4.66.4
- traitlets==5.14.3
- traits==6.4.3
- trame-client==3.1.0
- trame-jupyter-extension==2.1.1
- trame-server==3.0.1
- trame==3.6.2
- transformers==4.51.1
- triton==2.3.1
- types-python-dateutil==2.9.0.20240316
- typeshed-client==2.7.0
- typing-extensions==4.12.1
- tzdata==2024.1
- uri-template==1.3.0
- urllib3==2.2.1
- wandb==0.17.1
- wcwidth==0.2.13
- webcolors==24.6.0
- webencodings==0.5.1
- websocket-client==1.8.0
- werkzeug==3.0.3
- wheel==0.43.0
- widgetsnbextension==4.0.11
- wrapt==1.16.0
- wslink==2.0.5
- xgboost==2.0.3
- xxhash==3.5.0
- y-py==0.6.2
- yarl==1.9.4
- ypy-websocket==0.8.4
- yte==1.5.4
- zipp==3.19.2
- zope.interface==6.4.post2
